package org.openmrs.module.irbm25;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Loads the clinical lexicon resources (generated by tools/build_lexicon.py)
 * from the module classpath. These resources drive the clinical tokenizer:
 *
 * <ul>
 *   <li>{@code clinical/negation_terms.txt} — single-word negation markers that
 *       must survive stopword removal;</li>
 *   <li>{@code clinical/multiword_terms.txt} — multi-word concepts collapsed
 *       into a single token;</li>
 *   <li>{@code clinical/abbreviations.tsv} — abbreviation → expansion,
 *       applied symmetrically at index and query time;</li>
 *   <li>{@code clinical/synonyms.tsv} — term → synonym list, query-side only.</li>
 * </ul>
 */
public class ClinicalLexicon {
	
	private final Set<String> negationTerms = new TreeSet<>();
	private final List<String> multiwordTerms = new ArrayList<>();
	private final Map<String, String> abbreviations = new LinkedHashMap<>();
	private final Map<String, List<String>> synonyms = new LinkedHashMap<>();
	
	public ClinicalLexicon() throws IOException {
		loadNegationTerms();
		loadMultiwordTerms();
		loadAbbreviations();
		loadSynonyms();
	}
	
	public Set<String> getNegationTerms() {
		return negationTerms;
	}
	
	public List<String> getMultiwordTerms() {
		return multiwordTerms;
	}
	
	public Map<String, String> getAbbreviations() {
		return abbreviations;
	}
	
	public Map<String, List<String>> getSynonyms() {
		return synonyms;
	}
	
	private void loadNegationTerms() throws IOException {
		try (BufferedReader r = reader("clinical/negation_terms.txt")) {
			String line;
			while ((line = r.readLine()) != null) {
				line = line.trim();
				if (!line.isEmpty()) {
					negationTerms.add(line);
				}
			}
		}
	}
	
	private void loadMultiwordTerms() throws IOException {
		try (BufferedReader r = reader("clinical/multiword_terms.txt")) {
			String line;
			while ((line = r.readLine()) != null) {
				line = line.trim();
				if (!line.isEmpty()) {
					multiwordTerms.add(line);
				}
			}
		}
	}
	
	private void loadAbbreviations() throws IOException {
		try (BufferedReader r = reader("clinical/abbreviations.tsv")) {
			String line;
			while ((line = r.readLine()) != null) {
				int tab = line.indexOf('\t');
				if (tab < 0) {
					continue;
				}
				String abbr = line.substring(0, tab).trim();
				String expansion = line.substring(tab + 1).trim();
				if (!abbr.isEmpty() && !expansion.isEmpty()) {
					abbreviations.put(abbr, expansion);
				}
			}
		}
	}
	
	private void loadSynonyms() throws IOException {
		try (BufferedReader r = reader("clinical/synonyms.tsv")) {
			String line;
			while ((line = r.readLine()) != null) {
				int tab = line.indexOf('\t');
				if (tab < 0) {
					continue;
				}
				String term = line.substring(0, tab).trim().toLowerCase();
				String syn = line.substring(tab + 1).trim();
				if (term.isEmpty() || syn.isEmpty()) {
					continue;
				}
				List<String> list = new ArrayList<>();
				for (String s : syn.split("\\|")) {
					s = s.trim().toLowerCase();
					if (!s.isEmpty()) {
						list.add(s);
					}
				}
				synonyms.put(term, list);
			}
		}
	}
	
	private BufferedReader reader(String resource) throws IOException {
		InputStream in = getClass().getClassLoader().getResourceAsStream(resource);
		if (in == null) {
			throw new IOException("Missing clinical lexicon resource: " + resource);
		}
		return new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
	}
	
	/** Build a map from a phrase's first word to the phrase (split into words). */
	public Map<String, List<String[]>> indexMultiwordTerms() {
		Map<String, List<String[]>> index = new HashMap<>();
		for (String phrase : multiwordTerms) {
			String[] words = phrase.split("\\s+");
			if (words.length >= 2) {
				index.computeIfAbsent(words[0], k -> new ArrayList<>()).add(words);
			}
		}
		return index;
	}
	
	/** Convenience: immutable view of the abbreviation keys, sorted. */
	public List<String> abbreviationKeys() {
		return Collections.unmodifiableList(new ArrayList<>(abbreviations.keySet()));
	}
}
